name: CodeQL

on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  Analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: github/codeql-action/init@v1
      with:
        languages: javascript
        config-file: ./.github/codeql-config.yml
      
    - uses: github/codeql-action/analyze@v1
